export enum BatchRequestTypes {
    IMPRESSION = 1, //IMPRESIONES
    CATALOGS= 2, //LISTA DE CATALOGOS
    CATALOGS_REF= 3, //LISTA DE CATALOGOS SIN PRECIO (SOLO REFERENCIAS)
};

export enum BatchRequestTypesStatus {
    PENDING = 1, //IMPRESIONES
    COMPLETED= 2, //LISTA DE CATALOGOS
    EXECUTED= 3, //EJECUTADO
    FAILED=4, //FALLIDA
};
