export enum EventStatus {
    PENDING = 1, //RESERVADA
    CONFIRMED= 2, //CONFIRMADA
    PRINTED= 3, //IMPRESA
    SENT= 4, //ENVIADA
    RECONCILED= 5, //CONCILIADA
    CANCELED = 6, //ANULADA
    FINISHED = 7, //FINALIZADA
    UPDATED = 8, //ACTUALIZADA
};
