export enum FIELD_OPTIONS {
    REFERENCE_KEY = 'REFERENCE_KEY',
    MATERIALS = 'MATERIALS',
    PROVIDERS = 'PROVIDERS',
    ORDERS_ORIGIN = 'ORDERS_ORIGIN',
    MAYORISTA_DISC = 'MAYORISTA_DISC',
    OP_GROUPS= 'GROUPS',
    CUSTOMER_OBSERVATIONS= 'CUSTOMER_OBSERVATIONS',
    ORDER_OBSERVATIONS= 'ORDER_OBSERVATIONS',
    TEMPLATE_MENTIONS= 'TEMPLATE_MENTIONS',
    BANKS= 'BANKS',
};