export enum TemplatesRegisters {
    EXPORT_CATALOG_LIST = 'PRINT_CATALOG_LIST', //IMPRESION DE CATALOGOS
    PRINT_ORDER = 'PRINT_ORDER', //IMPRESION DE ORDENES
    OFFICE_PDF = 'OFFICE_PDF', //PDF PARA IMPRIMIR EN DESPACHO
    PRINT_ORDER_TEST = 'PRINT_ORDER_TEST', //IMPRESION DE ORDENES (PRUEBA)
    EXPORT_CATALOG_LIST_TEST = 'PRINT_CATALOG_LIST_TEST', //IMPRESION DE CATALOGOS
};
