export const EXPORTER_INTERRAPIDISIMO_CD = 'EXPORTER_INTERRAPIDISIMO_CD';
export const EXPORTER_SERVIENTREGA_CD = 'EXPORTER_SERVIENTREGA_CD';
export const EXPORTER_POSTVENTA = 'EXPORTER_POSTVENTA';
export const EXPORTER_ELECTRONIC_BILL = 'EXPORTER_ELECTRONIC_BILL';
export const EXPORTER_CONCILIATES = 'EXPORTER_CONCILIATES';
export const EXPORTER_OFFICES = 'EXPORTER_OFFICES';
export const EXPORTER_OFFICES_MENSAJERO = 'EXPORTER_OFFICES_MENSAJERO';
export const EXPORTER_CUSTOMERS = 'EXPORTER_CUSTOMERS';
